name: Workflow 1 - Dependent Jobs

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Print build start
        run: echo "Building application..."
      - name: Simulate build
        run: |
          echo "Compiling..."
          sleep 2
          echo "Build complete "

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Print test start
        run: echo "Running tests..."
      - name: Simulate tests
        run: |
          echo "Executing unit tests..."
          sleep 2
          echo "All tests passed "

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Print deploy start
        run: echo "Deploying application..."
      - name: Simulate deploy
        run: |
          echo "Uploading artifacts..."
          sleep 2
          echo "Deployment successful 🚀"
